# Generated by Django 3.0.4 on 2020-04-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppersPoint', '0002_auto_20200401_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='laptops',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ShoppersPoint.Products'),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ShoppersPoint.Products'),
        ),
    ]
