# Generated by Django 3.0.4 on 2020-04-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppersPoint', '0003_auto_20200402_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_count',
        ),
    ]
