# Generated by Django 3.0.4 on 2020-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppersPoint', '0004_remove_products_image_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='graphics_ram',
        ),
    ]
