# Generated by Django 3.0.4 on 2020-04-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppersPoint', '0005_remove_laptops_graphics_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='ssd',
        ),
    ]
