# Generated by Django 3.0.4 on 2020-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppersPoint', '0007_auto_20200404_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
